namespace Recaman

/-! # The finite arithmetic core of the periodic candidate no-go

In the non-truncated candidate regime, encode addition by `+1` and
subtraction by `-1`.  If a period has length `p`, the candidate increment at
clock `n` is

```text
sign * (n + 1) - 1.
```

For a balanced period, the one-period drift at phase zero is therefore the
weighted sign sum with weights `1, ..., p`, minus `p`.  Rotating the phase
past a sign `s` changes the drift by exactly `p * s`.  The definitions below
generate all `p` phase drifts from these two facts.

The main finite theorem is `balanced_periodPhaseDrifts_sum`: the sum of the
phase drifts is `-p^2`.  Thus a nonempty balanced period has a negative-drift
phase.  No sign-size, Recaman history, freshness, reachability, or run-length
assumption is used.  In particular, the theorem applies to signs in
`{-1, +1}`, but the finite identity is valid for every balanced integer
list.

This module deliberately stops at the finite core.  Transferring its three
sign-sum cases to an eventually periodic infinite walk requires a separate
sequence/asymptotic interface; that infrastructure is not assumed here.
-/

/-- The sign sum weighted by the positions `1, ..., signs.length`. -/
def periodWeightedSignSum : List Int → Int
  | [] => 0
  | sign :: signs => sign + periodWeightedSignSum signs + signs.sum

/-- The sum of all strict prefix sums of a period.

For `[s₀, ..., sₚ₋₁]`, this is
`0 + s₀ + (s₀ + s₁) + ... + (s₀ + ... + sₚ₋₂)`. -/
def periodPrefixMass : List Int → Int
  | [] => 0
  | sign :: signs => (signs.length : Int) * sign + periodPrefixMass signs

/-- Starting from one phase drift, advance once for each sign by the
balanced-period recurrence `next = current + period * sign`. -/
def periodPhaseDriftsFrom (period current : Int) : List Int → List Int
  | [] => []
  | sign :: signs =>
      current :: periodPhaseDriftsFrom period (current + period * sign) signs

/-- The one-period drift at phase zero. -/
def periodDrift (signs : List Int) : Int :=
  periodWeightedSignSum signs - (signs.length : Int)

/-- The phase-zero drift followed by the phase drifts generated by moving
successively past the signs of the period. -/
def periodPhaseDrifts (signs : List Int) : List Int :=
  periodPhaseDriftsFrom (signs.length : Int) (periodDrift signs) signs

/-- Move the first sign to the end, i.e. rotate the period by one phase. -/
def movePeriodHead : List Int → List Int
  | [] => []
  | sign :: signs => signs ++ [sign]

/-- The first `count` cyclic rotations of a period. -/
def periodRotationsFrom : Nat → List Int → List (List Int)
  | 0, _ => []
  | count + 1, signs =>
      signs :: periodRotationsFrom count (movePeriodHead signs)

/-- All cyclic phase words of a period, in phase order. -/
def periodRotations (signs : List Int) : List (List Int) :=
  periodRotationsFrom signs.length signs

@[simp] theorem periodWeightedSignSum_nil :
    periodWeightedSignSum [] = 0 := rfl

@[simp] theorem periodWeightedSignSum_cons (sign : Int) (signs : List Int) :
    periodWeightedSignSum (sign :: signs) =
      sign + periodWeightedSignSum signs + signs.sum := rfl

@[simp] theorem periodPrefixMass_nil : periodPrefixMass [] = 0 := rfl

@[simp] theorem periodPrefixMass_cons (sign : Int) (signs : List Int) :
    periodPrefixMass (sign :: signs) =
      (signs.length : Int) * sign + periodPrefixMass signs := rfl

@[simp] theorem periodPhaseDriftsFrom_nil (period current : Int) :
    periodPhaseDriftsFrom period current [] = [] := rfl

@[simp] theorem periodPhaseDriftsFrom_cons
    (period current sign : Int) (signs : List Int) :
    periodPhaseDriftsFrom period current (sign :: signs) =
      current :: periodPhaseDriftsFrom period (current + period * sign) signs :=
  rfl

@[simp] theorem periodPhaseDriftsFrom_length
    (period current : Int) (signs : List Int) :
    (periodPhaseDriftsFrom period current signs).length = signs.length := by
  induction signs generalizing current with
  | nil => rfl
  | cons sign signs ih => simp [periodPhaseDriftsFrom, ih]

@[simp] theorem periodPhaseDrifts_length (signs : List Int) :
    (periodPhaseDrifts signs).length = signs.length := by
  simp [periodPhaseDrifts]

@[simp] theorem periodRotationsFrom_length (count : Nat) (signs : List Int) :
    (periodRotationsFrom count signs).length = count := by
  induction count generalizing signs with
  | zero => rfl
  | succ count ih => simp [periodRotationsFrom, ih]

@[simp] theorem periodRotations_length (signs : List Int) :
    (periodRotations signs).length = signs.length := by
  simp [periodRotations]

/-- Appending a list shifts all of its weights by the length of the first
list. -/
theorem periodWeightedSignSum_append (xs ys : List Int) :
    periodWeightedSignSum (xs ++ ys) =
      periodWeightedSignSum xs + periodWeightedSignSum ys +
        (xs.length : Int) * ys.sum := by
  induction xs with
  | nil => simp [periodWeightedSignSum]
  | cons x xs ih =>
      simp only [List.cons_append, periodWeightedSignSum_cons, ih,
        List.sum_append, List.length_cons]
      have hlen : ((xs.length + 1 : Nat) : Int) =
          (xs.length : Int) + 1 := by
        omega
      rw [hlen]
      simp only [Int.add_mul]
      omega

/-- Weighted signs plus all strict prefix sums give `p` copies of the
ordinary sign sum. -/
theorem periodWeightedSignSum_add_prefixMass (signs : List Int) :
    periodWeightedSignSum signs + periodPrefixMass signs =
      (signs.length : Int) * signs.sum := by
  induction signs with
  | nil => rfl
  | cons sign signs ih =>
      simp only [periodWeightedSignSum_cons, periodPrefixMass_cons,
        List.length_cons, List.sum_cons]
      have hlen : ((signs.length + 1 : Nat) : Int) =
          (signs.length : Int) + 1 := by
        omega
      rw [hlen, Int.mul_add]
      simp only [Int.add_mul]
      rw [← ih]
      omega

/-- Summing the affine phase recurrence separates the initial drift from
the strict-prefix contribution. -/
theorem periodPhaseDriftsFrom_sum
    (period current : Int) (signs : List Int) :
    (periodPhaseDriftsFrom period current signs).sum =
      (signs.length : Int) * current + period * periodPrefixMass signs := by
  induction signs generalizing current with
  | nil => simp [periodPhaseDriftsFrom, periodPrefixMass]
  | cons sign signs ih =>
      simp only [periodPhaseDriftsFrom_cons, List.sum_cons, ih,
        List.length_cons, periodPrefixMass_cons]
      have hlen : ((signs.length + 1 : Nat) : Int) =
          (signs.length : Int) + 1 := by
        omega
      rw [hlen, Int.mul_add, Int.mul_add]
      simp only [Int.add_mul]
      rw [Int.mul_left_comm (signs.length : Int) period sign]
      omega

/-- **Balanced cyclic-drift identity.**  Over all phases of a balanced
period, the one-period drifts sum to `-p^2`. -/
theorem balanced_periodPhaseDrifts_sum
    (signs : List Int) (hbalanced : signs.sum = 0) :
    (periodPhaseDrifts signs).sum =
      -((signs.length : Int) * (signs.length : Int)) := by
  unfold periodPhaseDrifts periodDrift
  rw [periodPhaseDriftsFrom_sum]
  calc
    (signs.length : Int) *
          (periodWeightedSignSum signs - (signs.length : Int)) +
        (signs.length : Int) * periodPrefixMass signs =
      (signs.length : Int) *
          (periodWeightedSignSum signs + periodPrefixMass signs) -
        (signs.length : Int) * (signs.length : Int) := by
          rw [Int.mul_sub, Int.mul_add]
          omega
    _ = (signs.length : Int) *
          ((signs.length : Int) * signs.sum) -
        (signs.length : Int) * (signs.length : Int) := by
          rw [periodWeightedSignSum_add_prefixMass]
    _ = -((signs.length : Int) * (signs.length : Int)) := by
          rw [hbalanced]
          simp

theorem exists_negative_of_sum_negative {xs : List Int}
    (hsum : xs.sum < 0) : ∃ x ∈ xs, x < 0 := by
  induction xs with
  | nil => simp at hsum
  | cons x xs ih =>
      by_cases hx : x < 0
      · exact ⟨x, by simp, hx⟩
      · have htail : xs.sum < 0 := by
          simp only [List.sum_cons] at hsum
          omega
        obtain ⟨y, hyMem, hy⟩ := ih htail
        exact ⟨y, by simp [hyMem], hy⟩

/-- A nonempty balanced period has a phase whose one-period drift is
strictly negative. -/
theorem balanced_periodPhaseDrifts_has_negative
    (signs : List Int) (hne : signs ≠ [])
    (hbalanced : signs.sum = 0) :
    ∃ drift ∈ periodPhaseDrifts signs, drift < 0 := by
  apply exists_negative_of_sum_negative
  rw [balanced_periodPhaseDrifts_sum signs hbalanced]
  have hlenNat : 0 < signs.length := List.ne_nil_iff_length_pos.mp hne
  have hlen : (0 : Int) < (signs.length : Int) := by omega
  have hsquare : (0 : Int) <
      (signs.length : Int) * (signs.length : Int) := Int.mul_pos hlen hlen
  omega

@[simp] theorem movePeriodHead_length (signs : List Int) :
    (movePeriodHead signs).length = signs.length := by
  cases signs with
  | nil => rfl
  | cons sign signs => simp [movePeriodHead]

@[simp] theorem movePeriodHead_sum (signs : List Int) :
    (movePeriodHead signs).sum = signs.sum := by
  cases signs with
  | nil => rfl
  | cons sign signs =>
      simp [movePeriodHead, List.sum_append, Int.add_comm]

/-- Before imposing balance, rotating past the head changes the period drift
by `p * head - signSum`. -/
theorem movePeriodHead_drift_difference (sign : Int) (signs : List Int) :
    periodDrift (movePeriodHead (sign :: signs)) -
        periodDrift (sign :: signs) =
      ((sign :: signs).length : Int) * sign - (sign :: signs).sum := by
  unfold periodDrift
  simp only [movePeriodHead, periodWeightedSignSum_append,
    periodWeightedSignSum_cons]
  simp [periodWeightedSignSum]
  simp only [Int.add_mul]
  omega

/-- For a balanced period, the drift recurrence used by
`periodPhaseDrifts` is exactly the effect of one cyclic rotation. -/
theorem balanced_movePeriodHead_drift (sign : Int) (signs : List Int)
    (hbalanced : (sign :: signs).sum = 0) :
    periodDrift (movePeriodHead (sign :: signs)) =
      periodDrift (sign :: signs) +
        ((sign :: signs).length : Int) * sign := by
  have hdiff := movePeriodHead_drift_difference sign signs
  rw [hbalanced] at hdiff
  omega

/-- The first recursive phase transition is the actual drift of the
one-place cyclic rotation.  Since rotation preserves length and sign sum,
the same lemma applies at every later phase. -/
theorem balanced_periodPhaseDrifts_cons (sign : Int) (signs : List Int)
    (hbalanced : (sign :: signs).sum = 0) :
    periodPhaseDrifts (sign :: signs) =
      periodDrift (sign :: signs) ::
        periodPhaseDriftsFrom ((sign :: signs).length : Int)
          (periodDrift (movePeriodHead (sign :: signs))) signs := by
  unfold periodPhaseDrifts
  rw [periodPhaseDriftsFrom_cons]
  rw [balanced_movePeriodHead_drift sign signs hbalanced]

/-- The recurrence-generated drifts are the actual drifts of successive
cyclic rotations.  The split `front ++ back` records the unconsumed heads
and the already wrapped suffix, making the cyclic index audit structural. -/
theorem periodPhaseDriftsFrom_eq_rotations
    (front back : List Int) (hbalanced : (front ++ back).sum = 0) :
    periodPhaseDriftsFrom ((front ++ back).length : Int)
        (periodDrift (front ++ back)) front =
      (periodRotationsFrom front.length (front ++ back)).map periodDrift := by
  induction front generalizing back with
  | nil => rfl
  | cons sign front ih =>
      have hbalancedCons : (sign :: (front ++ back)).sum = 0 := by
        simpa only [List.cons_append] using hbalanced
      have hbalancedRotated : (front ++ (back ++ [sign])).sum = 0 := by
        simp only [List.sum_append, List.sum_cons, List.sum_nil, Int.add_zero]
          at hbalancedCons ⊢
        omega
      have hdrift :
          periodDrift (front ++ (back ++ [sign])) =
            periodDrift (sign :: (front ++ back)) +
              ((sign :: (front ++ back)).length : Int) * sign := by
        simpa only [List.cons_append, movePeriodHead, List.append_assoc] using
          balanced_movePeriodHead_drift sign (front ++ back) hbalancedCons
      simp only [List.cons_append, List.length_cons,
        periodPhaseDriftsFrom_cons, periodRotationsFrom, List.map_cons]
      apply congrArg (periodDrift (sign :: (front ++ back)) :: ·)
      rw [show movePeriodHead (sign :: (front ++ back)) =
          front ++ (back ++ [sign]) by
        simp [movePeriodHead, List.append_assoc]]
      have hperiod : (((front ++ back).length + 1 : Nat) : Int) =
          ((sign :: (front ++ back)).length : Int) := by
        simp
      rw [hperiod, ← hdrift]
      have hperiodRotated : ((sign :: (front ++ back)).length : Int) =
          ((front ++ (back ++ [sign])).length : Int) := by
        simp [List.length_append]
        omega
      rw [hperiodRotated]
      exact ih (back ++ [sign]) hbalancedRotated

/-- On a balanced word, `periodPhaseDrifts` is exactly the map of
`periodDrift` over all cyclic rotations. -/
theorem balanced_periodPhaseDrifts_eq_rotations
    (signs : List Int) (hbalanced : signs.sum = 0) :
    periodPhaseDrifts signs = (periodRotations signs).map periodDrift := by
  have h := periodPhaseDriftsFrom_eq_rotations signs [] (by
    simpa using hbalanced)
  simpa [periodPhaseDrifts, periodRotations] using h

/-- The `-p^2` identity stated directly for actual cyclic rotations. -/
theorem balanced_periodRotations_drift_sum
    (signs : List Int) (hbalanced : signs.sum = 0) :
    ((periodRotations signs).map periodDrift).sum =
      -((signs.length : Int) * (signs.length : Int)) := by
  rw [← balanced_periodPhaseDrifts_eq_rotations signs hbalanced]
  exact balanced_periodPhaseDrifts_sum signs hbalanced

/-- A nonempty balanced period has an actual cyclic phase word with
negative one-period drift. -/
theorem balanced_periodRotations_has_negative
    (signs : List Int) (hne : signs ≠ [])
    (hbalanced : signs.sum = 0) :
    ∃ phase ∈ periodRotations signs, periodDrift phase < 0 := by
  obtain ⟨drift, hmem, hnegative⟩ :=
    balanced_periodPhaseDrifts_has_negative signs hne hbalanced
  rw [balanced_periodPhaseDrifts_eq_rotations signs hbalanced] at hmem
  simp only [List.mem_map] at hmem
  obtain ⟨phase, hphase, hphaseDrift⟩ := hmem
  exact ⟨phase, hphase, hphaseDrift ▸ hnegative⟩

/- Small-period index audits. -/
example : periodPhaseDrifts ([1, -1] : List Int) = [-3, -1] := by
  decide

example : periodRotations ([1, -1] : List Int) =
    [[1, -1], [-1, 1]] := by
  decide

example : periodPhaseDrifts ([1, -1, -1, 1] : List Int) =
    [-4, 0, -4, -8] := by
  decide

end Recaman
