import Recaman.PermanentAboveCorridorPrefixSuccessorCoverage
import Recaman.ChunkedTraceCertificate

namespace Recaman

noncomputable section

/-! # Clock-112 target pin

The clock-112 replay band is `152 < target ∧ target ≤ 261`.  The residual
certificate below is designed for an external exact-history generator and a
kernel-sound chunked trace checker through time 2622.  A
separate explicit table records one occurrence clock for every value in that
band except 223.  Thus the replay's global `target_missing` field leaves 223
as the unique possible target.

The external data become usable only after the checker authenticates every
orbit branch and every witness-array lookup.  No native evaluation is used.
-/

/-- A lookup in the chronological value array of an authenticated checkpoint
gives an occurrence in the ordinary Recamán history. -/
theorem TraceMachine.Represents.occurs_of_value_lookup
    {machine : TraceMachine} {horizon time value : Nat}
    (hrep : machine.Represents (stateAt horizon))
    (hlookup : machine.values[time]? = some value) :
    ∃ witness, a witness = value := by
  have hparts := getElem?_eq_some_iff.mp hlookup
  have hmem : value ∈ machine.values.toList := by
    rw [← hparts.2]
    exact Array.getElem_mem_toList hparts.1
  have hreverse : value ∈ machine.values.toList.reverse :=
    List.mem_reverse.mpr hmem
  rw [hrep.values_reverse] at hreverse
  have hhistory : value ∈ valuesThrough horizon := by
    exact hreverse
  rcases mem_valuesThrough_iff.mp hhistory with ⟨witness, _, hvalue⟩
  exact ⟨witness, hvalue⟩

/-! ## Explicit empirical input boundary

The table below is deliberately plain data.  Each pair is `(value, first
occurrence clock)`.  It is generated by an external exact-history replay, but
becomes usable by the proof only through `Clock112ExactHistoryCertificate`,
whose fields connect every listed clock to an authenticated `TraceMachine`.

The long stretches are affine comb pieces plus a few boundary points.
Expanding them here keeps the remaining checker input unambiguous and avoids
a large `∀ Fin` decision.
-/

def clock112TargetOccurrenceWitnessTimes : List (Nat × Nat) := [
  (153, 74), (154, 72), (155, 70), (156, 68), (157, 66),
  (158, 88), (159, 90), (160, 92), (161, 94), (162, 96), (163, 98),
  (164, 100),
  (165, 337), (166, 335), (167, 333), (168, 331), (169, 329),
  (170, 327), (171, 325), (172, 323), (173, 321), (174, 319),
  (175, 317), (176, 315), (177, 313), (178, 311), (179, 309),
  (180, 307),
  (181, 1409), (182, 1407), (183, 1405), (184, 1403), (185, 1401),
  (186, 1399), (187, 1397), (188, 1395), (189, 1393), (190, 1391),
  (191, 1389), (192, 1387), (193, 1385), (194, 1383), (195, 1381),
  (196, 1379), (197, 1377), (198, 1375), (199, 1373), (200, 1371),
  (201, 1369), (202, 1367), (203, 1365), (204, 1363),
  (205, 2622), (206, 2620), (207, 2618), (208, 2616), (209, 2614),
  (210, 2612), (211, 2610), (212, 2608), (213, 2606), (214, 2604),
  (215, 2602), (216, 2600), (217, 2598), (218, 2596), (219, 2594),
  (220, 2592), (221, 2590), (222, 2588),
  (224, 67), (225, 69), (226, 71), (227, 73), (228, 75),
  (229, 285), (230, 283), (231, 281), (232, 279), (233, 277),
  (234, 275), (235, 273), (236, 271), (237, 269), (238, 267),
  (239, 265), (240, 263), (241, 261), (242, 259), (243, 257),
  (244, 255), (245, 253), (246, 251), (247, 249), (248, 247),
  (249, 245), (250, 243), (251, 241), (252, 239), (253, 237),
  (254, 235),
  (255, 1345), (256, 195), (257, 193),
  (258, 119), (259, 121), (260, 123), (261, 109)
]

/-- The same witness data as a small piecewise-affine lookup.  The exceptional
input 223 is intentionally irrelevant: every use carries `value ≠ 223`. -/
def clock112TargetOccurrenceWitnessTime (value : Nat) : Nat :=
  if value ≤ 157 then 380 - 2 * value
  else if value ≤ 164 then 2 * value - 228
  else if value ≤ 180 then 667 - 2 * value
  else if value ≤ 204 then 1771 - 2 * value
  else if value ≤ 222 then 3032 - 2 * value
  else if value ≤ 228 then 2 * value - 381
  else if value ≤ 254 then 743 - 2 * value
  else if value = 255 then 1345
  else if value ≤ 257 then 707 - 2 * value
  else if value = 258 then 119
  else if value ≤ 260 then 2 * value - 397
  else 109

/-- The expanded table and the compressed lookup agree.  This is only a
small arithmetic/list check and does not unfold the Recamán sequence. -/
theorem clock112TargetOccurrenceWitnessTimes_match_lookup :
    clock112TargetOccurrenceWitnessTimes.all (fun entry =>
      clock112TargetOccurrenceWitnessTime entry.1 == entry.2) = true := by
  decide

/-- The exact residual expected from a balanced trace checker.  The checker
must authenticate one checkpoint through clock 2622 and all 108 explicit
chronological-array lookups. -/
structure Clock112ExactHistoryCertificate where
  machine : TraceMachine
  represents : machine.Represents (stateAt 2622)
  witness_lookup : ∀ value, 153 ≤ value → value ≤ 261 → value ≠ 223 →
    machine.values[clock112TargetOccurrenceWitnessTime value]? = some value

namespace TerminalExactDischargeReplayCertificate

variable {target start : Nat} {parent : PhaseSearchNode}
variable {source : PermanentTailDischargeReturnCertificate target start parent}

/-- Once the explicit exact-history residual is authenticated, a clock-112
replay has exactly one possible missing target: 223. -/
theorem target_eq_223_of_crossingTime_eq_112
    (r : TerminalExactDischargeReplayCertificate source)
    (hclock : r.crossingTime = 112)
    (history : Clock112ExactHistoryCertificate) :
    target = 223 := by
  have hpins := r.clock112_historical_downcross_pins hclock
  by_cases heq : target = 223
  · exact heq
  · have hlow : 153 ≤ target := by omega
    have hhigh : target ≤ 261 := hpins.2.2.2
    have hlookup := history.witness_lookup target hlow hhigh heq
    have hoccurs := history.represents.occurs_of_value_lookup hlookup
    exact False.elim (r.target_missing hoccurs)

end TerminalExactDischargeReplayCertificate

end

end Recaman
