import Recaman.Basic

namespace Recaman

/-!
An exact seeded counterexample to extending the blocked-comb survival ratio
to arbitrary finite histories. This is not a counterexample on `stateAt`.

At clock 2160 the seed is followed by two subtractions into a maximal
level-1/2 prelanding run: n = 2162, hPrev = 135, J = 25. Its single tooth
lands at (c,v) = (2213,59), with 58 and the popup test 4487 already seen.
Although 16*59 = 944 < 945 = 7*135, the same no-wrap segment later lands
at (2229,1). The first subsequent wrap is at clock 2232.

The seed satisfies cardinality, triangular range, and canonical parity.
The escape uses a blocked level-three candidate, visits level seven, and
then takes seven fresh subtractions. A bound based only on the initial
level-5/4 phase or on the prelanding run cannot cover this continuation.
-/

def seededSurvivalSeen : List Nat :=
  [0, 58, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95, 98, 101,
   104, 107, 110, 113, 116, 119, 122, 125, 128, 131, 134,
   4487, 6620, 6700, 6703, 8919]

/-- Offset zero is absolute clock 2160. Every later state is generated by
the actual greedy transition, with no intervention in its history. -/
def seededSurvivalState : Nat → State
  | 0 => ⟨6620, seededSurvivalSeen⟩
  | k + 1 => step (2161 + k) (seededSurvivalState k)

def seededSurvivalResidue (k : Nat) : Nat :=
  (seededSurvivalState k).value % (2160 + k)

set_option maxRecDepth 100000 in
set_option maxHeartbeats 5000000 in
/-- Full finite payload: seed bounds, exact run, genuine blocked one-tooth
popup, no wrap through the next landing, and strict ratio violation.
The quantification is over this seeded trajectory, not the canonical one. -/
theorem seededSurvival_ratio_counterexample :
    0 ∈ seededSurvivalSeen ∧
    6620 ∈ seededSurvivalSeen ∧
    seededSurvivalSeen.Nodup ∧
    seededSurvivalSeen.length ≤ 2160 + 1 ∧
    (∀ i : Fin seededSurvivalSeen.length,
      seededSurvivalSeen[i.1] ≤ 2160 * (2160 + 1) / 2) ∧
    6620 % 2 = (2160 * (2160 + 1) / 2) % 2 ∧
    (seededSurvivalState 0).value / 2160 = 3 ∧
    (seededSurvivalState 1).value / 2161 = 2 ∧
    (∀ k : Fin 26,
      (seededSurvivalState (2 + 2 * k.1)).value = 2297 - k.1) ∧
    (∀ k : Fin 25,
      (seededSurvivalState (3 + 2 * k.1)).value = 4460 + k.1) ∧
    (seededSurvivalState 53).value = 59 ∧
    58 ∈ (seededSurvivalState 53).seen ∧
    2 * 2213 + 59 + 2 ∈ (seededSurvivalState 53).seen ∧
    2218 < (seededSurvivalState 57).value ∧
    (seededSurvivalState 57).value - 2218 ∈ (seededSurvivalState 57).seen ∧
    ¬ CanSubtract 2218 (seededSurvivalState 57) ∧
    (seededSurvivalState 62).value / 2222 = 7 ∧
    (∀ k : Fin 15,
      2214 + k.1 ≤ (seededSurvivalState (54 + k.1)).value) ∧
    (∀ k : Fin 71,
      seededSurvivalResidue (k.1 + 1) ≤ seededSurvivalResidue k.1) ∧
    (seededSurvivalState 69).value = 1 ∧
    seededSurvivalResidue 71 < seededSurvivalResidue 72 ∧
    135 = 59 + 1 + 3 * 25 ∧
    16 * 59 < 7 * 135 := by
  decide

set_option maxRecDepth 100000 in
set_option maxHeartbeats 5000000 in
/-- Between the level-three blockage at 2218 and the next late landing at
2229, the only positive blocked uses are at clocks 2220, 2221, and 2222,
with pairwise distinct candidates 6700, 8919, and 11139. Thus even one-use
resources do not rescue the survival ratio on these seeded histories. -/
theorem seededSurvival_one_use_resources :
    (∀ i : Fin 10,
      2219 + i.1 < (seededSurvivalState (58 + i.1)).value) ∧
    (∀ i : Fin 10,
      ((seededSurvivalState (58 + i.1)).value - (2219 + i.1) ∈
        (seededSurvivalState (58 + i.1)).seen) ↔
          (i.1 = 1 ∨ i.1 = 2 ∨ i.1 = 3)) ∧
    (seededSurvivalState 59).value - 2220 = 6700 ∧
    (seededSurvivalState 60).value - 2221 = 8919 ∧
    (seededSurvivalState 61).value - 2222 = 11139 ∧
    6700 ≠ 8919 ∧ 6700 ≠ 11139 ∧ 8919 ≠ 11139 := by
  decide

end Recaman
